import type { NextPage } from 'next'
import Head from 'next/head'
import type { GetServerSidePropsContext } from 'next'
import { useRouter } from 'next/router'

import { Stack, Table, Title, Alert, Select } from '@mantine/core'

import allIPhones from '../allIPhones'
import { getIPhoneProductAndStockInfo } from '../getIPhoneProductAndStockInfo'

import React, { useEffect, useState } from 'react'

import theme from '../theme'
const { available, unavailable } = theme.colors

const iPhoneTypes = allIPhones.reduce((prev: any, next: any) => {
  if (
    prev[prev.length - 1]?.model !== next.model ||
    prev[prev.length - 1]?.color !== next.color
  ) {
    prev.push({
      model: next.model,
      color: next.color,
    })
  }

  return prev
}, [])

const Cols = (props: any) => {
  const { appleStores }: { appleStores: any[] } = props

  return (
    <tr>
      {/* <th>{`ID`}</th> */}
      {['Model', 'Color', 'Capacity', 'Price'].map((colName, i) => (
        <th key={i}>{colName}</th>
      ))}
      {appleStores.map((appleStore, i) => (
        <th key={i}>{appleStore}</th>
      ))}
    </tr>
  )
}

const Home: NextPage = (props: any) => {
  const { iPhoneProductAndStockInfo, queryIPhoneType } = props

  const [appleStores, setAppleStores] = useState([])

  const router = useRouter()

  useEffect(() => {
    if (iPhoneProductAndStockInfo.length > 0) {
      const stores = iPhoneProductAndStockInfo[0]?.stores
      setAppleStores(stores.map((store: any) => store.address))
    }
  }, [])

  if (iPhoneProductAndStockInfo.length <= 0) {
    return (
      <Alert m={10} title="Error" color="red">
        {`O no, you've encountered an error, please refresh or try again later!`}
      </Alert>
    )
  }

  const rows = iPhoneProductAndStockInfo.map((iPhoneRow: any, i: number) => {
    const { productId, model, productInfo, stores } = iPhoneRow
    const {
      dimensionColor: color,
      dimensionCapacity: capacity,
      priceString: price,
    } = productInfo

    return (
      <tr key={i}>
        {/* <td>{productId}</td> */}
        {[model, color, capacity, price].map((colName, i) => (
          <td key={i}>{colName}</td>
        ))}
        {stores.map((store: any, j: number) => {
          const quote = store.storePickupQuote
          return (
            <td
              key={j}
              style={{
                backgroundColor: quote.includes('unavailable')
                  ? unavailable
                  : available,
              }}
            >
              {quote}
            </td>
          )
        })}
      </tr>
    )
  })

  const handleSelectIPhoneType = async (event: any) => {
    const model = event.match(/^[^\(]+/)[0].trim()
    const color = event.match(/(?<=\().*(?=\))/)[0].trim()

    router.push({
      pathname: router.pathname,
      query: {
        model,
        color,
      },
    })
  }

  return (
    <div>
      <Head>
        <title>{`Apple Store iPhone Tracker`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack spacing="md" m={10}>
        <Title>{`Apple Store iPhone Tracker`}</Title>
        <Select
          label=""
          defaultValue={
            queryIPhoneType.model && queryIPhoneType.color
              ? `${queryIPhoneType.model} (${queryIPhoneType.color})`
              : `${iPhoneTypes[0].model} (${iPhoneTypes[0].color})`
          }
          searchable
          nothingFound="No options"
          data={iPhoneTypes.map((iPhone: any) => ({
            value: `${iPhone.model} (${iPhone.color})`,
            label: `${iPhone.model} (${iPhone.color})`,
          }))}
          onChange={handleSelectIPhoneType}
          maxDropdownHeight={600}
        />
        <Table striped>
          <thead>
            <Cols appleStores={appleStores} />
          </thead>
          <tbody>{rows}</tbody>
        </Table>
      </Stack>
    </div>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { model, color } = context.query

  const queryIPhoneType = { model: model || null, color: color || null }

  const iPhoneProductAndStockInfo = await getIPhoneProductAndStockInfo(
    model && color ? queryIPhoneType : iPhoneTypes[0]
  )

  return {
    props: {
      iPhoneProductAndStockInfo,
      queryIPhoneType,
    },
  }
}

export default Home
